MobileShop/Models/Sanpham.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace MobileShop.Models
{
    public partial class Sanpham
    {
        public Sanpham()
        {
            Anhs = new HashSet<Anh>();
            Chitietdonhangs = new HashSet<Chitietdonhang>();
            Giohangs = new HashSet<Giohang>();
        }

        public int Masp { get; set; }
        public string Tensp { get; set; }
        public decimal? Giatien { get; set; }
        public int? Soluong { get; set; }
        public string Mota { get; set; }
        public int? Thesim { get; set; }
        public int? Bonhotrong { get; set; }
        public bool? Sanphammoi { get; set; }
        public int? Ram { get; set; }
        public string Anhbia { get; set; }
        public int? Mahang { get; set; }
        public string Hedieuhanh { get; set; }
        public string Manhinh { get; set; }
        public string Chip { get; set; }
        public string Dungluongpin { get; set; }
        public string Dosangtoida { get; set; }
        public string Dophangiai { get; set; }
        public string Kichthuoc { get; set; }

        public virtual Hangsanxuat MahangNavigation { get; set; }
        public virtual ICollection<Anh> Anhs { get; set; }
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual ICollection<Giohang> Giohangs { get; set; }
    }
}

MobileShop/Controllers/SanphamController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MobileShop.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace MobileShop.Controllers
{
    public class SanphamController : Controller
    {

        MobileShopContext context = new MobileShopContext();

        public ActionResult Index(int? page, int? Mahang, string? keyword)
        {
            if (Mahang == null)
            {
                if (keyword == null) keyword = "";
                if (page == null) page = 1;
                var sanpham = context.Sanphams.Where(s => s.Tensp.ToLower().Contains(keyword.ToLower())).OrderBy(x => x.Masp);
                int pageSize = 9;
                int pageNumber = (page ?? 1);
                ViewBag.Hangsanxuats = context.Hangsanxuats.ToList();
                if (HttpContext.Session.GetString("UserSession") != null)
                    TempData["User"] = JsonConvert.DeserializeObject<Nguoidung>(HttpContext.Session.GetString("UserSession"));
                return View(sanpham.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                if (keyword == null) keyword = "";
                if (page == null) page = 1;
                var sanpham = context.Sanphams.Where(s => s.Tensp.ToLower().Contains(keyword.ToLower()) && s.Mahang == Mahang).OrderBy(x => x.Masp);
                int pageSize = 9;
                int pageNumber = (page ?? 1);
                ViewBag.Hangsanxuats = context.Hangsanxuats.ToList();
                return View(sanpham.ToPagedList(pageNumber, pageSize));
            }
        }

        public IActionResult Detail(int id)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
                TempData["User"] = JsonConvert.DeserializeObject<Nguoidung>(HttpContext.Session.GetString("UserSession"));
            var sanpham = context.Sanphams.Find(id);
            ViewData["HangSanXuat"] = context.Hangsanxuats.ToList();
            ViewData["Anh"] = context.Anhs.ToList();
            return View(sanpham);
        }
    }
}

MobileShop/Views/Sanpham/Detail.cshtml
@model MobileShop.Models.Sanpham
@{
    ViewBag.Title = "Product Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var hangSanXuat = ViewData["HangSanXuat"] as List<Hangsanxuat>;
    var anh = ViewData["Anh"] as List<Anh>;
}

<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .checked {
            color: orange;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h2 class="mt-6" style="text-align:center; font-weight:bold; margin-top: 70px">Chi tiết sản phẩm</h2>
                <h3 class="card-title" style="font-weight:bold">Điện thoại @Model.Tensp</h3>
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-6">
                        <div class="white-box text-center"><img style="width:100%" src="@Url.Content(@Model.Anhbia)" class="img-responsive"></div>

                        <div class="slider-area">
                            <div class="block-slider block-slider4">
                                <ul class="" id="bxslider-home4">
                                    @foreach (Anh anhPhu in anh)
                                    {
                                        if (anhPhu.Masp == @Model.Masp)
                                        {
                                            <li>
                                                <img src="@Url.Content(anhPhu.Url)" alt="Slide">
                                            </li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-6">
                        <h3 class="box-title mt-5">@Model.Tensp</h3>

                        @foreach (Hangsanxuat hang in hangSanXuat)
                        {
                            if (hang.Mahang == @Model.Mahang)
                            {
                                <h4>Nhà sản xuất: @hang.Tenhang</h4>
                            }
                        }

                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <br />
                        <p>@Model.Mota</p>
                        <h2 style="color:red" class="mt-5">
                            $@Model.Giatien<small class="text-success"> (15% off)</small>
                        </h2>
                        <h4 style="color:orange">
                            @if (@Model.Sanphammoi == true)
                            {
                                <p>Hàng mới về</p>
                            }
                            else
                            {
                                <p>Hàng cũ</p>
                            }
                        </h4>
                        @if (Model.Soluong < 1)
                        {
                            <h5 style="color:red">Hết Hàng</h5>
                        }
                        else
                        {
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @Ma = Model.Masp }))
                            {
                                <input type="submit" value="Mua ngay" id="bgnGioHang" class=" fa fa-shopping-cart btn btn-primary btn-rounded"/>
                            }
                            <h3 class="box-title mt-5">Số lượng chỉ còn @Model.Soluong toàn quốc!</h3>
                        }
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th scope="row">Hệ điều hành: </th>
                                    <td>@Model.Hedieuhanh</td>
                                </tr>
                                <tr>
                                    <th scope="row">Màn hình: </th>
                                    <td>@Model.Manhinh "</td>
                                </tr>
                                <tr>
                                    <th scope="row">Chip: </th>
                                    <td>@Model.Chip</td>
                                </tr>
                                <tr>
                                    <th scope="row">Thẻ sim: </th>
                                    <td>@Model.Thesim eSIM, hỗ trợ 5G</td>
                                </tr>
                                <tr>
                                    <th scope="row">Bộ nhớ trong: </th>
                                    <td>@Model.Bonhotrong GB</td>
                                </tr>
                                <tr>
                                    <th scope="row">Ram: </th>
                                    <td>@Model.Ram GB</td>
                                </tr>
                                <tr>
                                    <th scope="row">Dung lượng pin: </th>
                                    <td>@Model.Dungluongpin mAh</td>
                                </tr>
                                <tr>
                                    <th scope="row">Độ sáng tối đa: </th>
                                    <td>@Model.Dosangtoida nits</td>
                                </tr>
                                <tr>
                                    <th scope="row">Độ phân giải: </th>
                                    <td>@Model.Dophangiai Pixels</td>
                                </tr>
                                <tr>
                                    <th scope="row">Kích thước: </th>
                                    <td>@Model.Kichthuoc (mm)</td>
                                </tr>
                            </tbody>
                        </table>

                        <ul class="list-unstyled">
                            <li><i class="fa fa-check text-success"></i> Trả góp 0%</li>
                            <li><i class="fa fa-check text-success"></i> Freeship toàn quốc</li>
                            <li><i class="fa fa-check text-success"></i> Hỗ trợ đổi trả trong 6 tháng</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

MobileShop/Views/Sanpham/Index.cshtml
@using MobileShop.Models
@model X.PagedList.IPagedList<MobileShop.Models.Sanpham>
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Product List";
}
<style>
    .active {
        background: red !important;
        color: #5a88ca;
    }
</style>
<div class="slider-area">
    <div class="block-slider block-slider4">
        <ul class="" id="bxslider-home4">
            <li>
                <img src="https://cdn.tgdd.vn/2021/11/banner/Aseri-830-300-830x300.png" alt="Slide">
            </li>
            <li>
                <img src="https://cdn.tgdd.vn/2021/11/banner/830-300-830x300-8.png" alt="Slide">
            </li>
            <li>
                <img src="https://cdn.tgdd.vn/2021/11/banner/830-300-830x300-6.png" alt="Slide">
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 p-0">
        <table class="table table-light table-hover border-bottom-10">
            <thead>
                <tr>
                    <th class="text-center navbar-brand bg-secondary"><b>Danh mục sản phẩm</b></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center bg-dark">
                        <a class="navbar-brand text-warning" href="/Sanpham"><b>Tất cả sản phẩm</b></a>
                    </td>
                </tr>
                @foreach (var item in ViewBag.Hangsanxuats)
                {
                    <tr>
                        <td class="text-center bg-dark">
                            @{ string tenhang = item.Tenhang;}
                            @Html.ActionLink(@tenhang, "Index", "Sanpham", new { Mahang = item.Mahang }, new { @class = "navbar-brand text-warning " })
                        </td>
                    </tr>
                }
            </tbody>
        </table><ul class="nav navbar-nav">
        </ul>
    </div>
    <div class="dt col-lg-9">
        <div class="dt col-lg-12">
            <div class="row">
                <form asp-controller="Sanpham" asp-action="Index" class="form-inline my-2 my-lg-0">
                    <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Nhập tên sản phẩm" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Tìm kiếm</button>
                </form>
                <h3 style="text-align: center; background-color: #5a88ca" border-radius: 30px; color: whitesmoke"> Danh sách sản phẩm </h3>
                @if (Model.Count == 0)
                {
                    <h1 style="text-align:center; color:darkred">Không có sản phẩm</h1>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4" style="padding: 5px;">
                            <div style="padding: 5px; border: 1px solid grey; background-color: lavender; border-radius: 20px; height: 450px; margin-bottom: 5px">
                                <div>
                                    <a href="/Sanpham/Detail/@item.Masp"><img style="width: 100%; margin-top: 15px; height: 300px;" src="@Url.Content(item.Anhbia)" /></a>
                                    <div class="p-4">
                                        <div class="text-center">
                                            <h4><a style="font-size:20px; color: #5a88ca; text-align: center" href="/Sanpham/Detail/@item.Masp">@item.Tensp</a></h4>
                                            <span>Giá: @item.Giatien</span>
                                        </div>
                                    </div>
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center">
                                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @Ma = item.Masp }))
                                            {
                                                if (item.Soluong < 1)
                                                {
                                                    <button disabled class="btn btn-outline-dark text-dark">
                                                        <i class="bi-cart-fill me-1"></i>Hết hàng
                                                    </button>
                                                }
                                                else
                                                {
                                                    <input class="btn btn-danger" type="submit" value="Mua hàng" id="bgnGioHang" />
                                                }
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="text-center" style="margin-top:20px">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    </div>
</div>